baseURL = "https://davemessinger.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Mess's Musings"
theme = "anatole"
summarylength = 10
enableEmoji = true
publishDir =  "../temp-blog/"


# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-167913852-1"

[params]
title = "Mess's Musings"
author = "David Messinger"
description = "My First Blog, take it easy on me ;)"
profilePicture = "images/profile.jpg"
keywords = "technology, crowdsourcing, future of work"
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/davidmessinger/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dmessing"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/dmessing"

## [[params.socialIcons]]
## icon = "fa-instagram"
## title = "instagram"
## url = "https://www.instagram.com/"

## [[params.socialIcons]]
## icon = "fa-envelope"
## title = "e-mail"
## url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

##  [[menu.main]]
## name = "Resume"
## weight = 300
## identifier = "resume"
## url = "/resume/"
